# Site settings
title: BUDS Lab
tag_text: Building and Urban Data Science Group at NUS
description: BUDS Lab is a new research group at the National University of Singapore that focuses on leveraging data sources from the built environment to improve energy efficiency conservation, comfort, safety and satisfaction of humans.

# Build settings
markdown: kramdown
exclude: ["README.md"]
sass:
  style: compressed
